### PR TITLE
Update from feat/6_clean to tumu (ie feat/6 merge, again)

### PR DESCRIPTION
**Pull request by utunga**
Sorry I did some terrible thigns merging too early so created a new feat/6 branch which we should probably switch to at this point

### CODE REVIEW

**Comment by jwu910** [comment]
Changes on this branch are a little hard to discern, are you able to do a `git pull --rebase origin/main` to make sure we're up to date?

Is this branch a copy of the other feat/6?

**Comment by utunga** [comment]
Actually dang it sorrry @jwu910 ..  why did this branch end up with conflicts (again)? I'm going to delete it.

The whole point of this branch was to *not* have conflicts. It's just a direct copy of feat/6 but when I created it, I swear it didn't have conflicts and was gonna let a clean 'rebase and merge' to merge back into main. 

FWIW I did a while ago I did `git pull --rebase origin/main`  on feat/6  (well actually i did it in two steps pulling main down then rebasing on local main - maybe that makes a difference?) and then pushed and it got rid of conflicts from feat/6 to allow a clean merge back to main but then about a minute later Karen was doing something and complaining that it wasn't allowing a clean merge so.. Honestly I dont know. Git is a mystery to me sometimes. Anyway I'm gonna delete this branch (and close this PR) because it ain't acheiving what I was trying to do

**Comment by jwu910** [comment]
It depends on what you're trying to achieve in terms of history preservation too.

If you're okay with lots of merge commits you don't need to have a rebase merge (rebase merges essentially rewrite history on top of target).

And depending on if devs are pushing directly to a branch vs PR from another feature branch or a fork.

If you want we can schedule some time and I can try to explain a little bit. Can get kinda long lol

**Comment by utunga** [comment]
BTW it `git pull --rebase origin master` is cleaner than 

```
git fetch origin            # Updates origin/master
git rebase origin/master    # Rebases current branch onto origin/master
```

**Pull request closed without merging**
