### PR TITLE
Add accurate timestamp and speech bubble icon to Ad card 

### PR DESCRIPTION
**Pull request by sarah-arrrgh**

### CODE REVIEW

**Review by utunga — APPROVED** [review]
Looks great to me. Should do the job. Everything is 'less than a minute ago' when i tested it because of the mock.. do'h. But I'm sure it works great! 

Thanks

**Comment by jwu910** [comment]
@all-contributors please add sarah-arrrgh for code

**Comment by jwu910** [comment]
oh hyphens seem to be bugged

**Comment by jwu910** [comment]
@all-contributors please add @sarah-arrrgh for code

**Comment by utunga** [comment]
@all-contributors please add @luandro  for code

**Comment by utunga** [comment]
@all-contributors add @DAHuerta for project-management

**Pull request merged**
